spring.application.name=product

server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kefir_db
spring.datasource.username=postgres
spring.datasource.password=Ghbdtnbr123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Defer datasource initialization
spring.jpa.defer-datasource-initialization=true

# Actuator Configuration
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health,info
management.health.db.enabled=true

# Logging
logging.level.com.example.sklad=INFO
logging.level.org.springframework.jdbc.core=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# CORS Configuration (??? ????????? ?? localhost:3000)
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true