# application.properties (AuthService)
server.port=8097
spring.application.name=auth-service

# Database - ????? ?? ?????????? ?????????
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/kefir_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Ghbdtnbr123!}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT - ????? ?? ??????????
jwt.secret=${JWT_SECRET:kefir_logistics_secret_key_2024_super_secure_jwt_token}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging
logging.level.com.Auth=${LOG_LEVEL:INFO}