# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/kefir_db
spring.datasource.username=postgres
spring.datasource.password=Ghbdtnbr123!
server.port=8081

# JPA - ?????? ??????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# ????????? ???????????????? ????????????
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ========== ??????????? ???? ==========
logging.level.com.example=INFO
logging.level.yand=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR
logging.level.org.apache=ERROR